- hosts: localhost
  pre_tasks:
    - name: check if we are running under WSL
      set_fact:
        is_wsl: "{{ 'microsoft' in ansible_kernel|lower }}"
    - name: install packages
      apt:
        name: "{{ apt_packages }}"
  roles:
    - amazon-ecr-credential-helper
    - awscli
    - aws-iam-authenticator
    - awslogs
    - aws-sam-cli
    - aws-vault
    - bat
    - borg
    - docker
    - fd
    - fzf
    - go
    - k9s
    - kubectl
    - kustomize
    - role: microk8s
      when: not is_wsl and ansible_memtotal_mb >= 3876
    - packer
    - pandoc
    - ripgrep
    - shellcheck
    - terraform
    - xsv
