- name: check version
  command: /usr/local/bin/aws --version
  failed_when: false
  changed_when: aws.rc > 0 or aws.stdout.split()[0] != "aws-cli/" + awscli_version
  register: aws
- when: aws.changed
  block:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tempfile
    - name: download package
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli_version }}.zip
        dest: "{{ tempfile.path }}/awscli-exe-linux-x86_64-{{ awscli_version }}.zip"
        checksum: "{{ awscli_checksum }}"
    - name: extract package
      unarchive:
        src: "{{ tempfile.path }}/awscli-exe-linux-x86_64-{{ awscli_version }}.zip"
        dest: "{{ tempfile.path }}"
        remote_src: yes
    - name: delete old version
      file:
        path: /opt/awscli
        state: absent
    - name: install package
      command: ./aws/install --install-dir /opt/awscli
      args:
        chdir: "{{ tempfile.path }}"
  always:
    - name: remove temporary directory
      file:
        path: "{{ tempfile.path }}"
        state: absent
