- name: install snap
  snap:
    name: microk8s
    classic: yes
- name: wait for readiness
  command: microk8s.status --wait-ready
  changed_when: false
  register: microk8s
- name: enable addons
  command: microk8s.enable {{ item }}
  when: "item + ': disabled' in microk8s.stdout"
  loop:
    - dns
    - storage
- name: add users to microk8s group
  user:
    name: "{{ item }}"
    groups:
      - microk8s
    append: yes
  loop: "{{ microk8s_users }}"
