- name: install snap
  snap:
    name: microk8s
    channel: "{{ microk8s_channel }}"
    classic: yes
- name: install addons
  include_tasks: addons.yml
  loop:
    - dns
    - storage
- name: add users to microk8s group
  user:
    name: "{{ item }}"
    groups:
      - microk8s
    append: yes
  loop: "{{ microk8s_users }}"
