- name: check version
  command: /usr/local/bin/rg --version
  failed_when: false
  changed_when: ripgrep.rc > 0 or ripgrep.stdout.split()[1] != ripgrep_version
  register: ripgrep
- when: ripgrep.changed
  block:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tempfile
    - name: download package
      get_url:
        url: https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz
        dest: "{{ tempfile.path }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz"
        checksum: "{{ ripgrep_checksum }}"
    - name: extract package
      unarchive:
        src: "{{ tempfile.path }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ tempfile.path }}"
        remote_src: yes
    - name: install binary
      copy:
        src: "{{ tempfile.path }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl/rg"
        dest: /usr/local/bin/rg
        remote_src: yes
        mode: 0755
  always:
    - name: remove temporary directory
      file:
        path: "{{ tempfile.path }}"
        state: absent
