- name: add apt key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: keyserver.ubuntu.com
- name: add apt repository
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] http://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
- name: install docker-ce-cli
  apt:
    name: docker-ce-cli
  when: is_wsl
- name: install docker-ce
  apt:
    name: docker-ce
  when: not is_wsl
- name: add users to docker group
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  loop: "{{ docker_users }}"
  when: not is_wsl
